# Test deployment with new SSH key configuration

services:
  readme-pwa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://tts.cloud.atemkeng.de/
    container_name: readme-pwa
    platform: linux/amd64
    image: readme-pwa:latest
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://tts.cloud.atemkeng.de
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
