services:
  # Development service
  dev:
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    command: npm run dev
    container_name: readme-pwa
    ports:
      - "3007:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3007
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Production service
  prod:
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_API_URL=https://tts.cloud.atemkeng.de/
    container_name: readme-pwa
    platform: linux/amd64
    image: atemnbobs/readme-pwa:v0.0.1

    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://tts.cloud.atemkeng.de
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
