version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - TTS_API_URL=http://45.94.111.107:6080/v1/audio/speech
      - WATCHPACK_POLLING=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: npm run dev
